
import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nabil
 */
public class piihgambarbuttonfullscreen extends javax.swing.JFrame {

    /**
     * Creates new form piihgambarbuttonfullscreen
     */
    public piihgambarbuttonfullscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JPanel();
        mwr = new javax.swing.JButton();
        tlp = new javax.swing.JButton();
        poy = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        image = new javax.swing.JPanel();
        tulip = new javax.swing.JLabel();
        peony = new javax.swing.JLabel();
        mawar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mwr.setText("Mawar");
        mwr.setPreferredSize(new java.awt.Dimension(150, 30));
        mwr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mwrActionPerformed(evt);
            }
        });
        button.add(mwr);

        tlp.setText("Tulip");
        tlp.setPreferredSize(new java.awt.Dimension(150, 30));
        tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlpActionPerformed(evt);
            }
        });
        button.add(tlp);

        poy.setText("Peony");
        poy.setPreferredSize(new java.awt.Dimension(150, 30));
        poy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poyActionPerformed(evt);
            }
        });
        button.add(poy);

        ext.setText("Exit");
        ext.setPreferredSize(new java.awt.Dimension(150, 30));
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        button.add(ext);

        getContentPane().add(button, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        tulip.setIcon(new javax.swing.ImageIcon("C:\\Users\\nabil\\OneDrive\\Dokumen\\NetBeansProjects\\AplikasiPenampilGambar\\img\\tulip.jpg")); // NOI18N
        image.add(tulip, "1");

        peony.setIcon(new javax.swing.ImageIcon("C:\\Users\\nabil\\OneDrive\\Dokumen\\NetBeansProjects\\AplikasiPenampilGambar\\img\\peony.jpg")); // NOI18N
        image.add(peony, "2");

        mawar.setIcon(new javax.swing.ImageIcon("C:\\Users\\nabil\\OneDrive\\Dokumen\\NetBeansProjects\\AplikasiPenampilGambar\\img\\mawar.jpg")); // NOI18N
        mawar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        image.add(mawar, "0");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void mwrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mwrActionPerformed
       CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "0");
    }//GEN-LAST:event_mwrActionPerformed

    private void tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlpActionPerformed
       CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "1");
    }//GEN-LAST:event_tlpActionPerformed

    private void poyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poyActionPerformed
       CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "2");
    }//GEN-LAST:event_poyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               piihgambarbuttonfullscreen fullFrame = new piihgambarbuttonfullscreen();
               
               GraphicsDevice device = 
                       GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            
               device.setFullScreenWindow(fullFrame);
               
               fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button;
    private javax.swing.JButton ext;
    private javax.swing.JPanel image;
    private javax.swing.JLabel mawar;
    private javax.swing.JButton mwr;
    private javax.swing.JLabel peony;
    private javax.swing.JButton poy;
    private javax.swing.JButton tlp;
    private javax.swing.JLabel tulip;
    // End of variables declaration//GEN-END:variables

