
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nabil
 */
public class pilihgambarbutton extends javax.swing.JFrame {

    /**
     * Creates new form pilihgambarbutton
     */
    public pilihgambarbutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JPanel();
        mawar = new javax.swing.JButton();
        tulip = new javax.swing.JButton();
        peony = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        image = new javax.swing.JPanel();
        gmawar = new javax.swing.JLabel();
        gpeony = new javax.swing.JLabel();
        gtulip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mawar.setBackground(new java.awt.Color(204, 204, 255));
        mawar.setText("Mawar");
        mawar.setPreferredSize(new java.awt.Dimension(100, 35));
        mawar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mawarActionPerformed(evt);
            }
        });
        button.add(mawar);

        tulip.setBackground(new java.awt.Color(204, 204, 255));
        tulip.setText("Tulip");
        tulip.setPreferredSize(new java.awt.Dimension(100, 35));
        tulip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulipActionPerformed(evt);
            }
        });
        button.add(tulip);

        peony.setBackground(new java.awt.Color(204, 204, 255));
        peony.setText("Peony");
        peony.setPreferredSize(new java.awt.Dimension(100, 35));
        peony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peonyActionPerformed(evt);
            }
        });
        button.add(peony);

        exit.setBackground(new java.awt.Color(204, 204, 255));
        exit.setText("Exit");
        exit.setPreferredSize(new java.awt.Dimension(100, 35));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        button.add(exit);

        getContentPane().add(button, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        gmawar.setIcon(new javax.swing.ImageIcon("C:\\Users\\nabil\\OneDrive\\Dokumen\\NetBeansProjects\\AplikasiPenampilGambar\\img\\mawar.jpg")); // NOI18N
        image.add(gmawar, "0");

        gpeony.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peony.jpg"))); // NOI18N
        image.add(gpeony, "2");

        gtulip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tulip.jpg"))); // NOI18N
        gtulip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        image.add(gtulip, "1");
        gtulip.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(817, 1063));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void peonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peonyActionPerformed
        CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "2");
    }//GEN-LAST:event_peonyActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void tulipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulipActionPerformed
         CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "1");
    }//GEN-LAST:event_tulipActionPerformed

    private void mawarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mawarActionPerformed
        CardLayout cl = (CardLayout)(image.getLayout());
        cl.show(image, "0");
        
    }//GEN-LAST:event_mawarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihgambarbutton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gmawar;
    private javax.swing.JLabel gpeony;
    private javax.swing.JLabel gtulip;
    private javax.swing.JPanel image;
    private javax.swing.JButton mawar;
    private javax.swing.JButton peony;
    private javax.swing.JButton tulip;
    // End of variables declaration//GEN-END:variables
}
