
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nabil
 */
public class pilihgambarcombobox extends javax.swing.JFrame {

    /**
     * Creates new form pilihgambarcombobox
     */
    public pilihgambarcombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pilihan = new javax.swing.JLabel();
        cbox = new javax.swing.JComboBox<>();
        image = new javax.swing.JPanel();
        mawar = new javax.swing.JLabel();
        tulip = new javax.swing.JLabel();
        peony = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        pilihan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan.setText("Pilih Gambar");
        jPanel1.add(pilihan);

        cbox.setBackground(new java.awt.Color(255, 204, 204));
        cbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Disini", "Mawar", "Tulip", "Peony" }));
        cbox.setPreferredSize(new java.awt.Dimension(150, 28));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });
        jPanel1.add(cbox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        mawar.setBackground(new java.awt.Color(255, 204, 204));
        mawar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mawar.jpg"))); // NOI18N
        image.add(mawar, "0");

        tulip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tulip.jpg"))); // NOI18N
        image.add(tulip, "1");

        peony.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peony.jpg"))); // NOI18N
        image.add(peony, "2");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
       CardLayout cardLayout = (CardLayout) image.getLayout();
        String selectedOption = (String) cbox.getSelectedItem();

       
        if (!"Pilih Disini".equals(selectedOption)) {
            switch (selectedOption) {
                case "Mawar":
                    cardLayout.show(image, "0");
                    break;
                case "Tulip":
                    cardLayout.show(image, "1");
                    break;
                case "Peony":
                    cardLayout.show(image, "2");
                    break;
                default:
                    // Handle the default case or do nothing
                    break;
            }
        }
    }//GEN-LAST:event_cboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihgambarcombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihgambarcombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihgambarcombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihgambarcombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihgambarcombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JPanel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mawar;
    private javax.swing.JLabel peony;
    private javax.swing.JLabel pilihan;
    private javax.swing.JLabel tulip;
    // End of variables declaration//GEN-END:variables
}

